# GitHub Branch Protection Configuration
# This file documents the recommended branch protection settings
# Apply these settings manually in GitHub repository settings or via GitHub API

# Main Branch Protection Rules
main:
  # Basic Protection
  enforce_admins: true
  required_status_checks:
    strict: true
    contexts:
      - '🧪 Tests & Code Quality'
      - '📱 Mobile Performance'
      - '🔒 Security Analysis'
      - '🚨 Infinite Loop Detection'
      - '📊 Bundle Analysis'
      - '🔍 TypeScript Check'
      - '🧹 Lint & Format'

  # Pull Request Requirements
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    require_last_push_approval: true
    bypass_pull_request_allowances:
      users: []
      teams: []

  # Additional Restrictions
  restrictions:
    users: []
    teams: []
    apps: []

  # Force Push Protection
  allow_force_pushes: false
  allow_deletions: false

  # Conversation Resolution
  required_conversation_resolution: true

# Develop Branch Protection Rules (if using GitFlow)
develop:
  enforce_admins: false
  required_status_checks:
    strict: true
    contexts:
      - '🧪 Tests & Code Quality'
      - '🚨 Infinite Loop Detection'
      - '🔍 TypeScript Check'

  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true

  allow_force_pushes: false
  allow_deletions: false

# Feature Branch Pattern Protection
feature/*:
  required_status_checks:
    strict: false
    contexts:
      - '🧪 Tests & Code Quality'
      - '🚨 Infinite Loop Detection'

# Hotfix Branch Pattern Protection
hotfix/*:
  required_status_checks:
    strict: true
    contexts:
      - '🧪 Tests & Code Quality'
      - '🔒 Security Analysis'
      - '🚨 Infinite Loop Detection'

  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: true

  allow_force_pushes: false
  allow_deletions: false
