/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  
  // Explicit safelist of used classes
  safelist: [
    "-translate-x-px",
    "absolute",
    "active:bg-sidebar-accent",
    "active:text-sidebar-accent-foreground",
    "after:absolute",
    "after:inset-y-0",
    "after:w-1",
    "align-middle",
    "animate-caret-blink",
    "animate-in",
    "animate-pulse",
    "animate-spin",
    "appearance-none",
    "aria-disabled:opacity-50",
    "aria-disabled:pointer-events-none",
    "aria-invalid:border-destructive",
    "aspect-square",
    "auto-rows-min",
    "backdrop-blur-sm",
    "basis-full",
    "bg-accent",
    "bg-background",
    "bg-border",
    "bg-card",
    "bg-foreground",
    "bg-muted",
    "bg-popover",
    "bg-primary",
    "bg-secondary",
    "bg-sidebar",
    "bg-sidebar-border",
    "bg-transparent",
    "block",
    "border",
    "border-b",
    "border-border",
    "border-destructive",
    "border-input",
    "border-l",
    "border-l-accent",
    "border-l-border",
    "border-primary",
    "border-r",
    "border-sidebar-border",
    "border-t",
    "border-transparent",
    "border-y",
    "border-y-transparent",
    "break-words",
    "capitalize",
    "caption-bottom",
    "container",
    "cursor-default",
    "cursor-pointer",
    "custom-class",
    "dark:bg-yellow-900",
    "dark:bg-yellow-950",
    "dark:border-yellow-800",
    "dark:hover:text-yellow-200",
    "dark:text-muted-foreground",
    "dark:text-yellow-100",
    "dark:text-yellow-200",
    "dark:text-yellow-400",
    "data-[active=true]:aria-invalid:border-destructive",
    "data-[active=true]:border-ring",
    "data-[active=true]:focus:bg-accent",
    "data-[active=true]:hover:bg-accent",
    "data-[active=true]:text-accent-foreground",
    "data-[active=true]:z-10",
    "data-[disabled]:opacity-50",
    "data-[disabled]:pointer-events-none",
    "data-[error=true]:text-destructive",
    "data-[inset]:pl-8",
    "data-[motion=from-end]:slide-in-from-right-52",
    "data-[motion=from-start]:slide-in-from-left-52",
    "data-[motion=to-end]:slide-out-to-right-52",
    "data-[motion=to-start]:slide-out-to-left-52",
    "data-[motion^=from-]:animate-in",
    "data-[motion^=from-]:fade-in",
    "data-[motion^=to-]:animate-out",
    "data-[motion^=to-]:fade-out",
    "data-[orientation=horizontal]:h-full",
    "data-[orientation=horizontal]:h-px",
    "data-[orientation=horizontal]:w-full",
    "data-[orientation=vertical]:flex-col",
    "data-[orientation=vertical]:h-full",
    "data-[orientation=vertical]:min-h-44",
    "data-[orientation=vertical]:w-auto",
    "data-[orientation=vertical]:w-full",
    "data-[orientation=vertical]:w-px",
    "data-[panel-group-direction=vertical]:after:h-1",
    "data-[panel-group-direction=vertical]:after:left-0",
    "data-[panel-group-direction=vertical]:after:translate-x-0",
    "data-[panel-group-direction=vertical]:after:w-full",
    "data-[panel-group-direction=vertical]:flex-col",
    "data-[panel-group-direction=vertical]:h-px",
    "data-[panel-group-direction=vertical]:w-full",
    "data-[placeholder]:text-muted-foreground",
    "data-[selected=true]:bg-accent",
    "data-[selected=true]:text-accent-foreground",
    "data-[side=bottom]:slide-in-from-top-2",
    "data-[side=left]:slide-in-from-right-2",
    "data-[side=right]:slide-in-from-left-2",
    "data-[side=top]:slide-in-from-bottom-2",
    "data-[state=active]:bg-background",
    "data-[state=active]:shadow-sm",
    "data-[state=checked]:bg-primary",
    "data-[state=checked]:border-primary",
    "data-[state=checked]:text-primary-foreground",
    "data-[state=closed]:animate-accordion-up",
    "data-[state=closed]:animate-out",
    "data-[state=closed]:duration-300",
    "data-[state=closed]:fade-out-0",
    "data-[state=closed]:zoom-out-95",
    "data-[state=hidden]:animate-out",
    "data-[state=hidden]:fade-out",
    "data-[state=open]:animate-accordion-down",
    "data-[state=open]:animate-in",
    "data-[state=open]:bg-accent",
    "data-[state=open]:bg-secondary",
    "data-[state=open]:duration-500",
    "data-[state=open]:fade-in-0",
    "data-[state=open]:text-accent-foreground",
    "data-[state=open]:text-muted-foreground",
    "data-[state=open]:zoom-in-90",
    "data-[state=open]:zoom-in-95",
    "data-[state=selected]:bg-muted",
    "data-[state=unchecked]:bg-input",
    "data-[state=unchecked]:translate-x-0",
    "data-[state=visible]:animate-in",
    "data-[state=visible]:fade-in",
    "data-[variant=destructive]:focus:text-destructive",
    "data-[variant=destructive]:text-destructive",
    "data-[variant=outline]:shadow-xs",
    "disabled:cursor-not-allowed",
    "disabled:opacity-50",
    "disabled:pointer-events-none",
    "ease-in-out",
    "ease-linear",
    "field-sizing-content",
    "file:bg-transparent",
    "file:border-0",
    "file:font-medium",
    "file:h-7",
    "file:inline-flex",
    "file:text-foreground",
    "file:text-sm",
    "fill-current",
    "fill-primary",
    "first:border-l",
    "first:rounded-l-md",
    "fixed",
    "flex",
    "flex-col",
    "flex-col-reverse",
    "flex-row",
    "flex-wrap",
    "focus-visible:border-ring",
    "focus-visible:outline-1",
    "focus-visible:outline-hidden",
    "focus-visible:outline-ring",
    "focus-visible:ring-1",
    "focus-visible:ring-2",
    "focus-visible:ring-4",
    "focus-visible:ring-offset-1",
    "focus-visible:ring-ring",
    "focus-within:relative",
    "focus-within:z-20",
    "focus:bg-accent",
    "focus:outline-hidden",
    "focus:ring-2",
    "focus:ring-offset-2",
    "focus:ring-ring",
    "focus:text-accent-foreground",
    "font-bold",
    "font-medium",
    "font-mono",
    "font-normal",
    "font-semibold",
    "ghost",
    "grid",
    "grid-rows-[auto_auto]",
    "group",
    "group-data-[collapsible=icon]:overflow-hidden",
    "group-data-[disabled=true]:opacity-50",
    "group-data-[disabled=true]:pointer-events-none",
    "group-data-[side=left]:-right-4",
    "group-data-[side=right]:left-0",
    "group-data-[state=open]:rotate-180",
    "group-data-[variant=floating]:border",
    "group-data-[variant=floating]:border-sidebar-border",
    "group-data-[variant=floating]:rounded-lg",
    "group-data-[variant=floating]:shadow-sm",
    "group-hover:opacity-100",
    "group-hover:text-primary",
    "grow",
    "h-[1.15rem]",
    "h-[18px]",
    "h-[calc(100%-1px)]",
    "h-[var(--radix-navigation-menu-viewport-height)]",
    "h-auto",
    "h-full",
    "h-px",
    "h-svh",
    "has-data-[variant=inset]:bg-sidebar",
    "has-disabled:opacity-50",
    "hidden",
    "hover:after:bg-sidebar-border",
    "hover:bg-accent",
    "hover:bg-sidebar-accent",
    "hover:opacity-100",
    "hover:ring-4",
    "hover:shadow-md",
    "hover:shadow-xl",
    "hover:text-accent-foreground",
    "hover:text-foreground",
    "hover:text-sidebar-accent-foreground",
    "hover:text-yellow-800",
    "hover:underline",
    "inline",
    "inline-flex",
    "ios-nav-bar",
    "ios-sheet",
    "ios-sheet-backdrop",
    "ios-tab-bar",
    "ios-touch-feedback",
    "isolate",
    "items-center",
    "items-end",
    "items-start",
    "items-stretch",
    "justify-around",
    "justify-between",
    "justify-center",
    "justify-end",
    "justify-items-start",
    "justify-self-end",
    "justify-start",
    "last:border-b-0",
    "last:rounded-r-md",
    "leading-none",
    "leading-relaxed",
    "leading-tight",
    "left-[50%]",
    "left-full",
    "lg:grid-cols-2",
    "lg:grid-cols-3",
    "lg:grid-cols-6",
    "list-none",
    "max-h-[300px]",
    "max-h-[80vh]",
    "max-w-[calc(100%-2rem)]",
    "max-w-lg",
    "max-w-max",
    "max-w-md",
    "max-w-sm",
    "md:absolute",
    "md:block",
    "md:flex",
    "md:grid-cols-2",
    "md:grid-cols-4",
    "md:text-sm",
    "md:w-auto",
    "min-h-[60px]",
    "min-h-[calc(100vh-200px)]",
    "min-h-screen",
    "min-h-svh",
    "min-w-[12rem]",
    "min-w-[16px]",
    "min-w-[18px]",
    "min-w-[24px]",
    "min-w-[8rem]",
    "ml-auto",
    "mt-auto",
    "mx-auto",
    "origin-top-center",
    "outline",
    "outline-hidden",
    "outline-none",
    "overflow-auto",
    "overflow-hidden",
    "overflow-x-auto",
    "overflow-x-hidden",
    "overflow-y-auto",
    "p-[3px]",
    "p-px",
    "pb-safe-area-bottom",
    "peer",
    "peer-disabled:cursor-not-allowed",
    "peer-disabled:opacity-50",
    "placeholder:text-muted-foreground",
    "pointer-events-none",
    "relative",
    "resize-none",
    "ring-offset-background",
    "ring-sidebar-ring",
    "rounded",
    "rounded-[2px]",
    "rounded-[4px]",
    "rounded-[inherit]",
    "rounded-full",
    "rounded-lg",
    "rounded-md",
    "rounded-sm",
    "rounded-tl-sm",
    "rounded-xl",
    "rounded-xs",
    "select-none",
    "selection:bg-primary",
    "selection:text-primary-foreground",
    "self-start",
    "shadow",
    "shadow-lg",
    "shadow-md",
    "shadow-none",
    "shadow-sm",
    "shadow-xl",
    "shadow-xs",
    "sidebar-wrapper-custom",
    "size-full",
    "sm:block",
    "sm:flex",
    "sm:flex-row",
    "sm:gap-3",
    "sm:inline",
    "sm:items-center",
    "sm:justify-end",
    "sm:max-w-lg",
    "sm:text-left",
    "sr-only",
    "tabular-nums",
    "text-[10px]",
    "text-[8px]",
    "text-accent",
    "text-balance",
    "text-base",
    "text-card-foreground",
    "text-center",
    "text-current",
    "text-destructive",
    "text-fg",
    "text-fg-secondary",
    "text-foreground",
    "text-left",
    "text-lg",
    "text-muted-foreground",
    "text-popover-foreground",
    "text-primary",
    "text-primary-foreground",
    "text-right",
    "text-secondary",
    "text-secondary-foreground",
    "text-sidebar-foreground",
    "text-sm",
    "text-white",
    "text-xs",
    "toaster",
    "top-[1px]",
    "top-[50%]",
    "top-[60%]",
    "top-full",
    "touch-manipulation",
    "touch-none",
    "tracking-tight",
    "tracking-widest",
    "transform",
    "transition",
    "transition-[color,box-shadow]",
    "transition-[left,right,width]",
    "transition-[margin,opacity]",
    "transition-[width]",
    "transition-all",
    "transition-colors",
    "transition-none",
    "transition-opacity",
    "transition-shadow",
    "transition-transform",
    "translate-x-[-50%]",
    "translate-x-px",
    "translate-y-[-50%]",
    "translate-y-[calc(-50%_-_2px)]",
    "truncate",
    "underline",
    "w-[100px]",
    "w-auto",
    "w-fit",
    "w-full",
    "w-px",
    "whitespace-nowrap",
    "z-[1]"
],
  
  theme: {
    extend: {
      // Only include used colors
      colors: {
        
      },
      
      // Only include used spacing
      spacing: {
        
      },
      
      // Only include used breakpoints
      screens: {
        'lg': '1024px',
        'md': '768px',
        'sm': '640px',
      },
    },
  },
  
  // Disable unused core plugins
  corePlugins: {
    
    
    
    
    // Disable heavy features
    backdropBlur: false,
    backdropBrightness: false,
    backdropContrast: false,
    backdropGrayscale: false,
    backdropHueRotate: false,
    backdropInvert: false,
    backdropOpacity: false,
    backdropSaturate: false,
    backdropSepia: false,
    
    // Disable complex layouts
    columns: false,
    breakAfter: false,
    breakBefore: false,
    breakInside: false,
  },
  
  plugins: [],
};
