# 💕 Cloudflare Pages configuration for Couple Connect
name = "couple-connect"
compatibility_date = "2024-08-14"

# Environment variables for production
[env.production.vars]
NODE_ENV = "production"
ENVIRONMENT = "production"
CLOUDFLARE_ANALYTICS_TOKEN = "YOUR_ANALYTICS_TOKEN_HERE"
CLOUDFLARE_IMAGES_ACCOUNT_HASH = "plxxk0i1H1TUBzR_H65xQ"
ENABLE_REAL_TIME_SYNC = "true"
ENABLE_ADVANCED_ANALYTICS = "true"
ENABLE_IMAGE_OPTIMIZATION = "true"

# D1 Database configuration for production
[[env.production.d1_databases]]
binding = "DB"
database_name = "couple-connect-db"
database_id = "your-database-id-here"

# Environment variables for preview
[env.preview.vars]
NODE_ENV = "development"
ENVIRONMENT = "preview"
CLOUDFLARE_ANALYTICS_TOKEN = "YOUR_PREVIEW_ANALYTICS_TOKEN_HERE"
CLOUDFLARE_IMAGES_ACCOUNT_HASH = "plxxk0i1H1TUBzR_H65xQ"
ENABLE_REAL_TIME_SYNC = "false"
ENABLE_ADVANCED_ANALYTICS = "true"
ENABLE_IMAGE_OPTIMIZATION = "true"

# D1 Database configuration for preview
[[env.preview.d1_databases]]
binding = "DB"
database_name = "couple-connect-db-preview"
database_id = "your-preview-database-id-here"
