# Cloudflare Pages configuration
name = "couple-connect"
compatibility_date = "2024-08-14"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "service-worker"
dir = "dist"
main = "./dist"

# Environment variables for production
[env.production.vars]
NODE_ENV = "production"

# Environment variables for preview
[env.preview.vars]
NODE_ENV = "development"

# Custom domains (uncomment and configure when ready)
# [[env.production.routes]]
# pattern = "couple-connect.com"
# zone_name = "couple-connect.com"

# Custom headers for security
[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"
