name: Docker Test

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  REGISTRY: docker.io
  IMAGE_NAME: couple-connect

jobs:
  docker-test:
    name: Build and Test Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:test .

      - name: Test Docker image
        run: |
          # Start container
          docker run -d -p 3000:80 --name test-container ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:test

          # Wait for health check
          timeout 30 bash -c 'while ! curl -f http://localhost:3000/health; do sleep 2; done'

          # Test main page
          curl -f http://localhost:3000/

          # Stop container
          docker stop test-container
          docker rm test-container

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:test
          echo "✅ Docker image pushed successfully!"
          echo "Run with: docker run -p 3000:80 ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:test"
